hashtags/accounts/urls.py
from django.conf.urls import patterns, url
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^login/$', views.LoginView.as_view(), name='login'),
]

hashtags/hashtags/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

import hashtags.views

urlpatterns = [
    url(r'^$', hashtags.views.home, name='home'),
    url(r'^tags/', include('tags.urls', namespace='tags')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^admin/', include(admin.site.urls)),
]

hashtags/tags/urls.py
from django.conf.urls import patterns, url
from django.contrib import admin

import tags.views

urlpatterns = [
    url(r'^(?P<tag>[\w\-]+)/$', tags.views.post_list, name='post_list'),
]

hashtags/accounts/models.py
from django.db import models

# Create your models here.

hashtags/tags/models.py
from django.db import models
from django.core.urlresolvers import reverse


class Post(models.Model):
    text = models.TextField(blank=True, null=True)


class Tag(models.Model):
    tag = models.CharField(max_length=150, unique=True)
    post = models.ManyToManyField(Post)

    def natural_key(self):
        return self.tag

    def get_absolute_url(self):
        return reverse('tags:post_list', kwargs={'tag': self.tag})

hashtags/accounts/forms.py
from django import forms


class PasswordField(forms.CharField):
    widget = forms.PasswordInput


class LoginForm(forms.Form):
    email = forms.EmailField(label='Your email')
    password = PasswordField()

hashtags/accounts/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic.edit import FormView
from django.core.urlresolvers import reverse_lazy

from accounts.forms import LoginForm


def login(request):
    return render(request, 'accounts/login.html')


class LoginView(FormView):
    template_name = 'accounts/login.html'
    form_class = LoginForm
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        return super(LoginView, self).form_valid(form)

hashtags/hashtags/views.py
# -*- coding: utf-8 -*-
from django.http import HttpResponse
from django.shortcuts import render

from tags.models import Post, Tag

import json


def home(request):
    if request.is_ajax() and request.GET.get('term'):
        result = []
        tags = Tag.objects.filter(tag__istartswith=request.GET['term'])
        for tag in tags:
            tags_ = {}
            tags_['id'] = tag.id
            tags_['label'] = tag.tag
            tags_['value'] = tag.tag
            tags_['href'] = tag.get_absolute_url()
            result.append(tags_)

        return HttpResponse(
            json.dumps(result),
            'application/json'
        )
    return render(request, 'home.html', {
        'posts': Post.objects.all(),
    })

hashtags/tags/views.py
from django.shortcuts import render
from tags.models import Tag


def post_list(request, tag):
    tag = Tag.objects.get(tag=tag)
    posts = tag.post.all()

    return render(request, 'tags/post_list.html', {
        'posts': posts,
    })

hashtags/accounts/templates/accounts/login.html
<span class="testLogin">
  loginpage
</span>

<form method="POST" action=''>
  {% csrf_token %}
  {{ form }}
  <input type="submit" value="Login" />
</form>

hashtags/hashtags/templates/_account_bar.html
{% if user.is_authenticated %}
{% else %}
  <a href="{% url 'accounts:login' %}" class="loginLink">
    <span>로그인</span>
  </a>
{% endif %}

hashtags/hashtags/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
  <head>
    <title>Hashtags</title>
  </head>
<body>
{% block topbar %}
  {% include "nav.html" %}
{% endblock %}

{% block post_list %}
{% endblock %}

{% block js %}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
  <script src="https://code.jquery.com/ui/1.12.0-rc.2/jquery-ui.min.js" 
          integrity="sha256-55Jz3pBCF8z9jBO1qQ7cIf0L+neuPTD1u7Ytzrp2dqo="
          crossorigin="anonymous"></script>
  <script type="text/javascript"
          src="{% static "js/jquery.autocomplete.js" %}"></script>
{% endblock %}


</body>
</html>

hashtags/hashtags/templates/home.html
{% extends 'base.html' %}

hashtags/hashtags/templates/nav.html
<header>
<div class="container">
  <div class="account-bar">
    {% block account_bar %}
      {% include "_account_bar.html" %}
    {% endblock %}
  </div>

  <input id="id_search_tag" name="search_tag" placeholder="검색" type="
text">
</div>
</header>

hashtags/tags/templates/tags/post_list.html
{% extends 'base.html' %}

{% block post_list %}
  <div class="post_list">
    {% for post in posts %}
      <p class="post">
        {{ post.text }}
      </p>
    {% endfor %}
  </div>
{% endblock %}